const data = {
	result: {
		multiTenancy: { isEnabled: true, sides: { host: 2, tenant: 1 } },
		session: {
			userId: null,
			tenantId: 1,
			impersonatorUserId: null,
			impersonatorTenantId: null,
			multiTenancySide: 1
		},
		localization: {
			currentCulture: { name: 'zh-Hans', displayName: '中文(简体)' },
			languages: [
				{
					name: 'en',
					displayName: 'English',
					icon: 'famfamfam-flags gb',
					isDefault: true,
					isDisabled: false,
					isRightToLeft: false
				},
				{
					name: 'es-MX',
					displayName: 'Español México',
					icon: 'famfamfam-flags mx',
					isDefault: false,
					isDisabled: false,
					isRightToLeft: false
				},
				{
					name: 'fr',
					displayName: 'Français',
					icon: 'famfamfam-flags fr',
					isDefault: false,
					isDisabled: false,
					isRightToLeft: false
				},
				{
					name: 'de',
					displayName: 'German',
					icon: 'famfamfam-flags de',
					isDefault: false,
					isDisabled: false,
					isRightToLeft: false
				},
				{
					name: 'it',
					displayName: 'Italiano',
					icon: 'famfamfam-flags it',
					isDefault: false,
					isDisabled: false,
					isRightToLeft: false
				},
				{
					name: 'nl',
					displayName: 'Nederlands',
					icon: 'famfamfam-flags nl',
					isDefault: false,
					isDisabled: false,
					isRightToLeft: false
				},
				{
					name: 'pt-BR',
					displayName: 'Português',
					icon: 'famfamfam-flags br',
					isDefault: false,
					isDisabled: false,
					isRightToLeft: false
				},
				{
					name: 'tr',
					displayName: 'Türkçe',
					icon: 'famfamfam-flags tr',
					isDefault: false,
					isDisabled: false,
					isRightToLeft: false
				},
				{
					name: 'ru',
					displayName: 'Русский',
					icon: 'famfamfam-flags ru',
					isDefault: false,
					isDisabled: false,
					isRightToLeft: false
				},
				{
					name: 'ar',
					displayName: 'العربية',
					icon: 'famfamfam-flags sa',
					isDefault: false,
					isDisabled: false,
					isRightToLeft: true
				},
				{
					name: 'zh-Hans',
					displayName: '简体中文',
					icon: 'famfamfam-flags cn',
					isDefault: false,
					isDisabled: false,
					isRightToLeft: false
				},
				{
					name: 'ja',
					displayName: '日本語',
					icon: 'famfamfam-flags jp',
					isDefault: false,
					isDisabled: false,
					isRightToLeft: false
				}
			],
			currentLanguage: {
				name: 'zh-Hans',
				displayName: '简体中文',
				icon: 'famfamfam-flags cn',
				isDefault: false,
				isDisabled: false,
				isRightToLeft: false
			},
			sources: [
				{ name: 'Abp', type: 'MultiTenantLocalizationSource' },
				{ name: 'AbpWeb', type: 'MultiTenantLocalizationSource' },
				{ name: 'AbpZero', type: 'MultiTenantLocalizationSource' },
				{ name: 'luna', type: 'MultiTenantLocalizationSource' }
			],
			values: {
				Abp: {
					AllOfThesePermissionsMustBeGranted: '您没有权限进行此操作,您需要以下权限: {0}',
					AtLeastOneOfThesePermissionsMustBeGranted: '您没有权限进行此操作,您至少需要下列权限的其中一项: {0}',
					CurrentUserDidNotLoginToTheApplication: '当前用户没有登录到系统！',
					DefaultFromSenderDisplayName: '默认发件人名字',
					DefaultFromSenderEmailAddress: '默认发件人邮箱地址',
					DefaultLanguage: '预设语言',
					DomainName: '域名',
					MainMenu: '主菜单',
					Password: '密码',
					ReceiveNotifications: '接收通知',
					SmtpHost: 'SMTP主机',
					SmtpPort: 'SMTP端口',
					TimeZone: '时区',
					UseDefaultCredentials: '使用默认验证',
					Username: '用户名',
					UseSSL: '使用SSL'
				},
				AbpWeb: {
					AreYouSure: '你确定吗?',
					Cancel: '取消',
					DefaultError: 'An error has occurred!',
					DefaultError401: 'You are not authenticated!',
					DefaultError403: 'You are not authorized!',
					DefaultError404: 'Resource not found!',
					DefaultErrorDetail: 'Error detail not sent by server.',
					DefaultErrorDetail401: 'You should be authenticated (sign in) in order to perform this operation.',
					DefaultErrorDetail403: 'You are not allowed to perform this operation.',
					DefaultErrorDetail404: 'The resource requested could not found on the server.',
					EntityNotFound: 'There is no entity {0} with id = {1}!',
					InternalServerError: '对不起,在处理您的请求期间,产生了一个服务器内部错误!',
					ValidationError: '您的请求无效!',
					ValidationNarrativeTitle: 'The following errors were detected during validation.',
					Yes: '确定'
				},
				AbpZero: {
					CanNotDeleteAdminUser: '不能删除默认管理员{0}!',
					CanNotDeleteStaticRole: '不能删除系统预定义角色: {0}',
					CanNotRenameAdminUser: '不能重命名默认管理员的用户名 {0}',
					Email: '邮箱',
					EmailSecurityCodeBody: '您的安全码是: {0}',
					EmailSecurityCodeSubject: '安全码',
					'Identity.ConcurrencyFailure': '乐观并发失败,对象已修改.',
					'Identity.DefaultError': '发生了一个未知的异常错误.',
					'Identity.DuplicateEmail': "邮箱地址 '{0}' 已被占用.",
					'Identity.DuplicateRoleName': "角色名称 '{0}' 已经被使用.",
					'Identity.DuplicateUserName': '名字{0}已被占用.',
					'Identity.InvalidEmail': "邮箱地址 '{0}' 不符合要求.",
					'Identity.InvalidPasswordHasherCompatibilityMode': '提供的哈希密码兼容模式无效.',
					'Identity.InvalidPasswordHasherIterationCount': '迭代次数必须是一个正整数.',
					'Identity.InvalidRoleName': "角色名称'{0}'无效.",
					'Identity.InvalidToken': '无效的token.',
					'Identity.InvalidUserName': '用户名{0}不符合要求, 只能包含字母和数字.',
					'Identity.LoginAlreadyAssociated': '登录的用户已存在.',
					'Identity.PasswordMismatch': '密码错误.',
					'Identity.PasswordRequiresDigit': "密码至少要包含一位数字 ('0'-'9').",
					'Identity.PasswordRequiresLower': "密码至少要包含一位小写字母 ('a'-'z').",
					'Identity.PasswordRequiresNonAlphanumeric': '密码必须包含一位非字母特殊符号或数字.',
					'Identity.PasswordRequiresUpper': "密码至少要包含一位大写字母 ('A'-'Z').",
					'Identity.PasswordTooShort': '密码至少要{0}位.',
					'Identity.RoleNotFound': '角色{0}不存在.',
					'Identity.UserAlreadyHasPassword': '用户已设置密码.',
					'Identity.UserAlreadyInRole': '用户已拥有此角色.',
					'Identity.UserLockedOut': '用户被锁定.',
					'Identity.UserLockoutNotEnabled': '对此用户，不能启用锁定.',
					'Identity.UserNameNotFound': '用户 {0} 不存在.',
					'Identity.UserNotInRole': '用户不包含此角色.',
					InvalidTenancyName: '租户名无效!',
					OrganizationUnitDuplicateDisplayNameWarning:
						'There is already an organization unit with name {0}. Two units with same name can not be created in same level.',
					RoleDisplayNameIsAlreadyTaken: '角色显示名称 {0}已被占用.',
					RoleNameIsAlreadyTaken: '角色名{0}已被占用.',
					Sms: '短信',
					SmsSecurityCodeMessage: '您的短信验证码是: {0}',
					TenancyNameIsAlreadyTaken: '租户名{0} 已被占用.'
				},
				luna: {
					About: '关于我们',
					Actions: 'Actions',
					AdminEmailAddress: 'Admin email address',
					Administration: 'Administration',
					AreYouSureWantToDelete: 'Are you sure want to delete {0}?',
					Back: '返回',
					CanBeEmptyToLoginAsHost: 'Can be empty to login as host.',
					Cancel: '取消',
					Change: '变更',
					ChangeTenant: '改变租户',
					ClearAll: 'Clear all',
					ClearOthers: 'Clear others',
					ConfirmPassword: 'Confirm password',
					CouldNotCompleteLoginOperation: 'Could not complete login operation. Please try again later.',
					CouldNotValidateExternalUser: 'Could not validate external user',
					Create: 'Create',
					CreateNewRole: 'Create new role',
					CreateNewTenant: '新租户',
					CreateNewUser: 'Create new user',
					CurrentTenant: '当前租户',
					DatabaseConnectionString: 'Database connection string',
					DefaultPasswordIs: 'Default password is {0}',
					Delete: 'Delete',
					DisplayName: 'Display Name',
					Edit: 'Edit',
					EditRole: 'Edit role',
					EditTenant: 'Edit tenant',
					EditUser: 'Edit user',
					EmailAddress: 'Email address',
					ForgotPassword: '忘记密码？',
					FormIsNotValidMessage: '部分输入信息不符合要求，请检查并改正..',
					FullName: 'Full name',
					HomePage: '主页',
					InvalidUserNameOrPassword: '用户名或密码无效',
					IsActive: 'Is active',
					LabelOptions: 'Label options',
					LeaveEmptyToSwitchToHost: '为空表示使用主机用户登录',
					LogIn: '登录',
					LoginFailed: '登录失败!',
					Loginwithexistingaccounts: '使用已有账户登录',
					Logout: 'Logout',
					MultiLevelMenu: 'Multi Level Menu',
					Name: 'Name',
					NameSurname: 'Name surname',
					No: 'No',
					NotSelected: '未选择',
					Off: 'Off',
					On: 'On',
					Optional: 'Optional',
					OrLoginWith: 'Or login with',
					Password: '密码',
					Permissions: 'Permissions',
					PleaseEnterLoginInformation: '请输入登录信息',
					PleaseWait: 'Please wait...',
					Refresh: 'Refresh',
					Register: '注册',
					RegisterFormUserNameInvalidMessage: "Please don't enter an email address for username.",
					RememberMe: '记住我',
					RoleDescription: 'Role description',
					RoleName: 'Role Name',
					Roles: 'Roles',
					Save: '保存',
					SavedSuccessfully: 'Saved successfully',
					Settings: 'Settings',
					Skins: 'Skins',
					StartTyping: 'Start Typing',
					SuccessfullyRegistered: 'Successfully registered',
					Surname: 'Surname',
					TenancyName: '租户名称',
					'TenantIdIsNotActive{0}': 'TenantId {0} is not active',
					TenantIsNotActive: '租户 {0} 未激活.',
					TenantName_Regex_Description:
						'Tenant name must be at least 2 chars, starts with a letter and continue with letter, number, dash or underscore.',
					TenantNameCanNotBeEmpty: '租户名不能为空',
					Tenants: 'Tenants',
					TenantSelection: 'Tenant Selection',
					TenantSelection_Detail: 'Please select one of the following tenants.',
					'ThereIsNoTenantDefinedWithName{0}': '租户 {0}不存在',
					ThisFieldIsRequired: 'This field is required',
					'UnknownTenantId{0}': 'Unknown tenantId {0}',
					UserDetails: 'User details',
					UserEmailIsNotConfirmedAndCanNotLogin: 'Your email address is not confirmed. You can not login.',
					UserIsNotActiveAndCanNotLogin: '用户 {0} 未激活，不能登录.',
					UserLockedOutMessage: 'The user account has been locked out. Please try again later.',
					UserName: '用户名',
					UserNameOrEmail: '用户名或邮箱地址',
					UserRoles: 'User roles',
					Users: 'Users',
					Version: 'Version',
					WaitingForActivationMessage: 'Your account is waiting to be activated by system admin.',
					WaitingForEmailActivation: 'Your email address should be activated',
					WellcomeMessage: '欢迎使用 luna!',
					Yes: 'Yes'
				}
			}
		},
		features: { allFeatures: {} },
		auth: {
			allPermissions: { 'Pages.Users': 'true', 'Pages.Roles': 'true', 'Pages.Tenants': 'true' },
			grantedPermissions: {}
		},
		nav: { menus: { MainMenu: { name: 'MainMenu', displayName: '主菜单', customData: null, items: [] } } },
		setting: {
			values: {
				'Abp.Localization.DefaultLanguageName': 'en',
				'Abp.Notifications.ReceiveNotifications': 'true',
				'Abp.Timing.TimeZone': 'UTC',
				'Abp.Zero.UserManagement.IsEmailConfirmationRequiredForLogin': 'false',
				'Abp.Zero.OrganizationUnits.MaxUserMembershipCount': '2147483647',
				'Abp.Zero.UserManagement.TwoFactorLogin.IsEnabled': 'true',
				'Abp.Zero.UserManagement.TwoFactorLogin.IsRememberBrowserEnabled': 'true',
				'Abp.Zero.UserManagement.TwoFactorLogin.IsEmailProviderEnabled': 'true',
				'Abp.Zero.UserManagement.TwoFactorLogin.IsSmsProviderEnabled': 'true',
				'Abp.Zero.UserManagement.UserLockOut.IsEnabled': 'true',
				'Abp.Zero.UserManagement.UserLockOut.MaxFailedAccessAttemptsBeforeLockout': '5',
				'Abp.Zero.UserManagement.UserLockOut.DefaultAccountLockoutSeconds': '300',
				'Abp.Zero.UserManagement.PasswordComplexity.RequireDigit': 'false',
				'Abp.Zero.UserManagement.PasswordComplexity.RequireLowercase': 'false',
				'Abp.Zero.UserManagement.PasswordComplexity.RequireNonAlphanumeric': 'false',
				'Abp.Zero.UserManagement.PasswordComplexity.RequireUppercase': 'false',
				'Abp.Zero.UserManagement.PasswordComplexity.RequiredLength': '3',
				'App.UiTheme': 'red'
			}
		},
		clock: { provider: 'unspecifiedClockProvider' },
		timing: {
			timeZoneInfo: {
				windows: {
					timeZoneId: 'UTC',
					baseUtcOffsetInMilliseconds: 0.0,
					currentUtcOffsetInMilliseconds: 0.0,
					isDaylightSavingTimeNow: false
				},
				iana: { timeZoneId: 'Etc/UTC' }
			}
		},
		security: { antiForgery: { tokenCookieName: 'XSRF-TOKEN', tokenHeaderName: 'X-XSRF-TOKEN' } },
		custom: {}
	},
	targetUrl: null,
	success: true,
	error: null,
	unAuthorizedRequest: false,
	__abp: true
};
